apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-release-nginx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: k8-training-website
          servicePort: 3000
      # - path: /api/?(.*)
      #   backend:
      #     serviceName: k8-training-api
      #     servicePort: 80