apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  # ingressClassName: nginx
  rules:
  - host : appsample.kamanoaws.com
    http:
      paths:
      - path: /home
        pathType: Prefix
        backend:
          service:
            name: myapp-service
            port:
              number: 3000
      # - path: /api/?(.*)
      #   backend:
      #     serviceName: k8-training-api
      #     servicePort: 80